# Generated by Django 2.2.12 on 2020-04-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lipids.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forcefields', '0001_initial'),
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('lmid', models.CharField(max_length=20, unique=True)),
                ('com_name', models.CharField(max_length=200, unique=True)),
                ('search_name', models.CharField(max_length=300, null=True)),
                ('sys_name', models.CharField(max_length=200, null=True)),
                ('iupac_name', models.CharField(max_length=500, null=True)),
                ('formula', models.CharField(max_length=30, null=True)),
                ('core', models.CharField(max_length=200, null=True)),
                ('main_class', models.CharField(max_length=200, null=True)),
                ('sub_class', models.CharField(max_length=200, null=True)),
                ('l4_class', models.CharField(blank=True, max_length=200, null=True)),
                ('pubchem_cid', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(null=True, upload_to=lipids.models.img_path, validators=[lipids.models.validate_file_extension, lipids.models.validate_img_size])),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itp_file', models.FileField(upload_to=lipids.models.file_path, validators=[lipids.models.validate_file_size])),
                ('gro_file', models.FileField(upload_to=lipids.models.file_path, validators=[lipids.models.validate_file_size])),
                ('version', models.CharField(help_text='YearAuthor', max_length=30)),
                ('head', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forcefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forcefields.Forcefield')),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Lipid')),
                ('reference', models.ManyToManyField(to='homepage.Reference')),
                ('software', models.ManyToManyField(to='forcefields.Software')),
            ],
        ),
        migrations.CreateModel(
            name='TopComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Topology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
