# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lipids.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('forcefields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('lmid', models.CharField(max_length=20, unique=True)),
                ('com_name', models.CharField(max_length=200, unique=True)),
                ('sys_name', models.CharField(max_length=200, null=True)),
                ('iupac_name', models.CharField(max_length=200, null=True)),
                ('formula', models.CharField(max_length=30, null=True)),
                ('main_class', models.CharField(max_length=200, null=True)),
                ('sub_class', models.CharField(max_length=200, null=True)),
                ('img', models.FileField(null=True, upload_to=lipids.models.directory_path)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(choices=[(b'GR', b'Gromacs')], default=b'GR', max_length=2)),
                ('itp_file', models.FileField(upload_to=lipids.models.directory_path)),
                ('gro_file', models.FileField(upload_to=lipids.models.directory_path)),
                ('map_file', models.FileField(upload_to=lipids.models.directory_path)),
                ('version', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('forcefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forcefields.Forcefield')),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Lipid')),
                ('reference', models.ManyToManyField(to='homepage.Reference')),
            ],
        ),
    ]
