# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='com_name',
            field=models.CharField(max_length=200),
        ),
    ]
