# Generated by Django 2.2.13 on 2021-02-04 06:28

from django.db import migrations, models
import django.db.models.deletion
import lipids.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyResidue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lipid',
            name='core',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='iupac_name',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='l4_class',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='lmid',
            field=models.CharField(max_length=20, unique=True, validators=[lipids.models.validate_lmid]),
        ),
        migrations.AlterField(
            model_name='lipid',
            name='main_class',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='name',
            field=models.CharField(max_length=4, unique=True, validators=[lipids.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='lipid',
            name='pubchem_cid',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='search_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='sub_class',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='sys_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResidueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.TopologyResidue')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Topology')),
            ],
        ),
        migrations.AddField(
            model_name='topology',
            name='residues',
            field=models.ManyToManyField(through='lipids.ResidueList', to='lipids.TopologyResidue'),
        ),
    ]
