# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0002_auto_20171024_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='lipid',
            name='com_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
