# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import lipids.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0004_auto_20171024_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='img',
            field=models.FileField(null=True, upload_to=lipids.models.img_path),
        ),
    ]
