# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 09:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipids', '0007_auto_20171122_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
