# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0008_lipid_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='version',
            field=models.CharField(help_text=b'YearAuthor', max_length=30),
        ),
    ]
