# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0009_auto_20180104_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='iupac_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
