# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0014_lipid_search_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='search_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
