# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0017_lipid_l4_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='core',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
