# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models

import lipids.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0018_lipid_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='gro_file',
            field=models.FileField(upload_to=lipids.models.file_path),
        ),
        migrations.AlterField(
            model_name='topology',
            name='itp_file',
            field=models.FileField(upload_to=lipids.models.file_path),
        ),
        migrations.AlterField(
            model_name='topology',
            name='map_file',
            field=models.FileField(upload_to=lipids.models.file_path),
        ),
        migrations.AlterField(
            model_name='topology',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR', b'Gromacs'), (b'NA', b'NAMD')], default=b'GR', max_length=2),
        ),
    ]
