# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0019_auto_20180122_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipid',
            name='l4_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
