# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-02 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0020_auto_20180418_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology',
            name='map_file',
        ),
    ]
