# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import lipids.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0025_auto_20180607_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='gro_file',
            field=models.FileField(upload_to=lipids.models.file_path),
        ),
    ]
