# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-16 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0030_auto_20181015_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
