# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-17 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0031_auto_20181016_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='TopComment',
        ),
    ]
