# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0011_auto_20181030_1333'),
        ('lipids', '0033_auto_20181030_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology',
            name='software',
        ),
        migrations.AddField(
            model_name='topology',
            name='software',
            field=models.ManyToManyField(to='forcefields.Software'),
        ),
    ]
