# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0034_auto_20181030_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='pubchem_cid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
