# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import lipids.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0035_lipid_pubchem_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='head',
            field=models.CharField(default='P8', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipid',
            name='img',
            field=models.ImageField(null=True, upload_to=lipids.models.img_path, validators=[lipids.models.validate_file_extension, lipids.models.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='topology',
            name='gro_file',
            field=models.FileField(upload_to=lipids.models.file_path, validators=[lipids.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='topology',
            name='itp_file',
            field=models.FileField(upload_to=lipids.models.file_path, validators=[lipids.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='topology',
            name='version',
            field=models.CharField(help_text='YearAuthor', max_length=30),
        ),
    ]
