# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import membranes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('lipids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('side', models.CharField(choices=[(b'UN', b'Unknown'), (b'UP', b'Upper leaflet'), (b'LO', b'Lower leaflet')], default=b'UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Membrane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equilibration', models.CharField(default=b'Not done', max_length=30)),
                ('mem_file', models.FileField(upload_to=membranes.models.directory_path)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('lipids', models.ManyToManyField(through='membranes.Composition', to='lipids.Topology')),
                ('reference', models.ManyToManyField(to='homepage.Reference')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='membrane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membranes.Membrane'),
        ),
        migrations.AddField(
            model_name='composition',
            name='topology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Topology'),
        ),
    ]
