# Generated by Django 2.2.13 on 2021-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembraneDoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='search_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='doi',
            field=models.ManyToManyField(blank=True, to='membranes.MembraneDoi'),
        ),
    ]
