# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membranes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrane',
            name='curator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membrane',
            name='equilibration',
            field=models.CharField(default=b'Not done', help_text=b'ex.: During 250 ns', max_length=30),
        ),
    ]
