# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0002_auto_20171122_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrane',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
