# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import membranes.models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0004_auto_20171122_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrane',
            name='mem_file',
            field=models.FileField(help_text=b'.pdb and .gro files are supported', upload_to=membranes.models.directory_path, validators=[membranes.models.validate_file_extension]),
        ),
    ]
