# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0006_auto_20180116_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrane',
            name='equilibration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
