# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import membranes.models


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0019_auto_20180122_1350'),
        ('homepage', '0007_auto_20171220_1313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forcefields', '0004_auto_20180122_1350'),
        ('membranes', '0007_auto_20180117_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembraneTopol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equilibration', models.PositiveIntegerField()),
                ('mem_file', models.FileField(help_text=b'.pdb and .gro files are supported', upload_to=membranes.models.directory_path, validators=[membranes.models.validate_file_extension])),
                ('nb_lipids', models.PositiveIntegerField()),
                ('version', models.CharField(help_text=b'YearAuthor', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forcefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forcefields.Forcefield')),
            ],
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='date',
        ),
        migrations.AddField(
            model_name='composition',
            name='lipid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lipids.Lipid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrane',
            name='organel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membrane',
            name='organism',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='number',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='composition',
            name='side',
            field=models.CharField(choices=[(b'UP', b'Upper leaflet'), (b'LO', b'Lower leaflet')], default=b'UP', max_length=2),
        ),
        migrations.AlterField(
            model_name='membrane',
            name='equilibration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='membrane',
            name='lipids',
            field=models.ManyToManyField(through='membranes.Composition', to='lipids.Lipid'),
        ),
        migrations.AlterField(
            model_name='membrane',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='membrane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membranes.Membrane'),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='reference',
            field=models.ManyToManyField(to='homepage.Reference'),
        ),
    ]
