# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0008_auto_20180212_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='topology',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='equilibration',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='mem_file',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='reference',
        ),
        migrations.AlterField(
            model_name='membrane',
            name='organel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='membrane',
            name='organism',
            field=models.CharField(max_length=30),
        ),
    ]
