# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipids', '0019_auto_20180122_1350'),
        ('membranes', '0010_auto_20180213_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembraneTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopolComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[(b'UP', b'Upper leaflet'), (b'LO', b'Lower leaflet')], default=b'UP', max_length=2)),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Lipid')),
            ],
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='organel',
        ),
        migrations.RemoveField(
            model_name='membrane',
            name='organism',
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='temperature',
            field=models.PositiveIntegerField(default=323),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topolcomposition',
            name='membrane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membranes.MembraneTopol'),
        ),
        migrations.AddField(
            model_name='topolcomposition',
            name='topology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipids.Topology'),
        ),
        migrations.AddField(
            model_name='membrane',
            name='tag',
            field=models.ManyToManyField(blank=True, to='membranes.MembraneTag'),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='lipids',
            field=models.ManyToManyField(through='membranes.TopolComposition', to='lipids.Lipid'),
        ),
    ]
