# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-03 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0011_auto_20180314_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='number',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
