# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0012_auto_20180403_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membranetopol',
            name='version',
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='name',
            field=models.CharField(default='Crowet2018_temp', max_length=30),
            preserve_default=False,
        ),
    ]
