# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0013_auto_20180403_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='membranetopol',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR', b'Gromacs'), (b'NA', b'NAMD')], default=b'GR', max_length=2),
        ),
    ]
