# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-09 15:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0014_membranetopol_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='membrane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membranes.Membrane'),
        ),
    ]
