# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0015_auto_20180409_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrane',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
