# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0016_auto_20180409_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrane',
            name='nb_liptypes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
