# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0017_membrane_nb_liptypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='nb_lipids',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
