# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-08 08:39
from __future__ import unicode_literals

from django.db import migrations, models

import membranes.models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0025_auto_20180607_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='membranetopol',
            name='compo_file',
            field=models.FileField(blank=True, null=True, upload_to=membranes.models.directory_path),
        ),
    ]
