# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0027_auto_20181004_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
