# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0030_auto_20181030_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='software',
            field=models.CharField(choices=[(b'GR45', b'Gromacs 4.5'), (b'GR50', b'Gromacs 5.0')], default=b'GR50', max_length=4),
        ),
    ]
