# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0011_auto_20181030_1333'),
        ('membranes', '0032_auto_20181104_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membranetopol',
            name='software',
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='software',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forcefields.Software'),
            preserve_default=False,
        ),
    ]
