# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import membranes.models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0034_auto_20181122_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembraneProt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='other_file',
            field=models.FileField(blank=True, help_text='Use a zip file containing these files', null=True, upload_to=membranes.models.directory_path, validators=[membranes.models.validate_otherfile_extension, membranes.models.validate_other_size]),
        ),
        migrations.AlterField(
            model_name='composition',
            name='side',
            field=models.CharField(choices=[('UP', 'Upper leaflet'), ('LO', 'Lower leaflet'), ('UP2', 'Upper leaflet 2'), ('LO2', 'Lower leaflet 2'), ('UP3', 'Upper leaflet 3'), ('LO3', 'Lower leaflet 3'), ('UP4', 'Upper leaflet 4'), ('LO4', 'Lower leaflet 4'), ('UP5', 'Upper leaflet 5'), ('LO5', 'Lower leaflet 5'), ('UP6', 'Upper leaflet 6'), ('LO6', 'Lower leaflet 6'), ('UP7', 'Upper leaflet 7'), ('LO7', 'Lower leaflet 7'), ('UP8', 'Upper leaflet 8'), ('LO8', 'Lower leaflet 8'), ('UP9', 'Upper leaflet 9'), ('LO9', 'Lower leaflet 9'), ('UP10', 'Upper leaflet 10'), ('LO10', 'Lower leaflet 10'), ('UP11', 'Upper leaflet 11'), ('LO11', 'Lower leaflet 11'), ('UP12', 'Upper leaflet 12'), ('LO12', 'Lower leaflet 12'), ('UP13', 'Upper leaflet 13'), ('LO13', 'Lower leaflet 13'), ('UP14', 'Upper leaflet 14'), ('LO14', 'Lower leaflet 14'), ('UP15', 'Upper leaflet 15'), ('LO15', 'Lower leaflet 15'), ('UP16', 'Upper leaflet 16'), ('LO16', 'Lower leaflet 16'), ('UP17', 'Upper leaflet 17'), ('LO17', 'Lower leaflet 17'), ('UP18', 'Upper leaflet 18'), ('LO18', 'Lower leaflet 18'), ('UP19', 'Upper leaflet 19'), ('LO19', 'Lower leaflet 19'), ('UP20', 'Upper leaflet 20'), ('LO20', 'Lower leaflet 20'), ('UP21', 'Upper leaflet 21'), ('LO21', 'Lower leaflet 21'), ('UP22', 'Upper leaflet 22'), ('LO22', 'Lower leaflet 22'), ('UP23', 'Upper leaflet 23'), ('LO23', 'Lower leaflet 23'), ('UP24', 'Upper leaflet 24'), ('LO24', 'Lower leaflet 24'), ('UP25', 'Upper leaflet 25'), ('LO25', 'Lower leaflet 25'), ('UP26', 'Upper leaflet 26'), ('LO26', 'Lower leaflet 26'), ('UP27', 'Upper leaflet 27'), ('LO27', 'Lower leaflet 27'), ('UP28', 'Upper leaflet 28'), ('LO28', 'Lower leaflet 28'), ('UP29', 'Upper leaflet 29'), ('LO29', 'Lower leaflet 29'), ('UP30', 'Upper leaflet 30'), ('LO30', 'Lower leaflet 30'), ('UP31', 'Upper leaflet 31'), ('LO31', 'Lower leaflet 31'), ('UP32', 'Upper leaflet 32'), ('LO32', 'Lower leaflet 32'), ('UP33', 'Upper leaflet 33'), ('LO33', 'Lower leaflet 33'), ('UP34', 'Upper leaflet 34'), ('LO34', 'Lower leaflet 34'), ('UP35', 'Upper leaflet 35'), ('LO35', 'Lower leaflet 35'), ('UP36', 'Upper leaflet 36'), ('LO36', 'Lower leaflet 36'), ('UP37', 'Upper leaflet 37'), ('LO37', 'Lower leaflet 37'), ('UP38', 'Upper leaflet 38'), ('LO38', 'Lower leaflet 38'), ('UP39', 'Upper leaflet 39'), ('LO39', 'Lower leaflet 39'), ('UP40', 'Upper leaflet 40'), ('LO40', 'Lower leaflet 40'), ('UP41', 'Upper leaflet 41'), ('LO41', 'Lower leaflet 41'), ('UP42', 'Upper leaflet 42'), ('LO42', 'Lower leaflet 42'), ('UP43', 'Upper leaflet 43'), ('LO43', 'Lower leaflet 43'), ('UP44', 'Upper leaflet 44'), ('LO44', 'Lower leaflet 44'), ('UP45', 'Upper leaflet 45'), ('LO45', 'Lower leaflet 45'), ('UP46', 'Upper leaflet 46'), ('LO46', 'Lower leaflet 46'), ('UP47', 'Upper leaflet 47'), ('LO47', 'Lower leaflet 47'), ('UP48', 'Upper leaflet 48'), ('LO48', 'Lower leaflet 48'), ('UP49', 'Upper leaflet 49'), ('LO49', 'Lower leaflet 49'), ('UP50', 'Upper leaflet 50'), ('LO50', 'Lower leaflet 50'), ('UP51', 'Upper leaflet 51'), ('LO51', 'Lower leaflet 51'), ('UNK', 'Not in leaflet')], default='UP', max_length=4),
        ),
        migrations.AlterField(
            model_name='topolcomposition',
            name='side',
            field=models.CharField(choices=[('UP', 'Upper leaflet'), ('LO', 'Lower leaflet'), ('UP2', 'Upper leaflet 2'), ('LO2', 'Lower leaflet 2'), ('UP3', 'Upper leaflet 3'), ('LO3', 'Lower leaflet 3'), ('UP4', 'Upper leaflet 4'), ('LO4', 'Lower leaflet 4'), ('UP5', 'Upper leaflet 5'), ('LO5', 'Lower leaflet 5'), ('UP6', 'Upper leaflet 6'), ('LO6', 'Lower leaflet 6'), ('UP7', 'Upper leaflet 7'), ('LO7', 'Lower leaflet 7'), ('UP8', 'Upper leaflet 8'), ('LO8', 'Lower leaflet 8'), ('UP9', 'Upper leaflet 9'), ('LO9', 'Lower leaflet 9'), ('UP10', 'Upper leaflet 10'), ('LO10', 'Lower leaflet 10'), ('UP11', 'Upper leaflet 11'), ('LO11', 'Lower leaflet 11'), ('UP12', 'Upper leaflet 12'), ('LO12', 'Lower leaflet 12'), ('UP13', 'Upper leaflet 13'), ('LO13', 'Lower leaflet 13'), ('UP14', 'Upper leaflet 14'), ('LO14', 'Lower leaflet 14'), ('UP15', 'Upper leaflet 15'), ('LO15', 'Lower leaflet 15'), ('UP16', 'Upper leaflet 16'), ('LO16', 'Lower leaflet 16'), ('UP17', 'Upper leaflet 17'), ('LO17', 'Lower leaflet 17'), ('UP18', 'Upper leaflet 18'), ('LO18', 'Lower leaflet 18'), ('UP19', 'Upper leaflet 19'), ('LO19', 'Lower leaflet 19'), ('UP20', 'Upper leaflet 20'), ('LO20', 'Lower leaflet 20'), ('UP21', 'Upper leaflet 21'), ('LO21', 'Lower leaflet 21'), ('UP22', 'Upper leaflet 22'), ('LO22', 'Lower leaflet 22'), ('UP23', 'Upper leaflet 23'), ('LO23', 'Lower leaflet 23'), ('UP24', 'Upper leaflet 24'), ('LO24', 'Lower leaflet 24'), ('UP25', 'Upper leaflet 25'), ('LO25', 'Lower leaflet 25'), ('UP26', 'Upper leaflet 26'), ('LO26', 'Lower leaflet 26'), ('UP27', 'Upper leaflet 27'), ('LO27', 'Lower leaflet 27'), ('UP28', 'Upper leaflet 28'), ('LO28', 'Lower leaflet 28'), ('UP29', 'Upper leaflet 29'), ('LO29', 'Lower leaflet 29'), ('UP30', 'Upper leaflet 30'), ('LO30', 'Lower leaflet 30'), ('UP31', 'Upper leaflet 31'), ('LO31', 'Lower leaflet 31'), ('UP32', 'Upper leaflet 32'), ('LO32', 'Lower leaflet 32'), ('UP33', 'Upper leaflet 33'), ('LO33', 'Lower leaflet 33'), ('UP34', 'Upper leaflet 34'), ('LO34', 'Lower leaflet 34'), ('UP35', 'Upper leaflet 35'), ('LO35', 'Lower leaflet 35'), ('UP36', 'Upper leaflet 36'), ('LO36', 'Lower leaflet 36'), ('UP37', 'Upper leaflet 37'), ('LO37', 'Lower leaflet 37'), ('UP38', 'Upper leaflet 38'), ('LO38', 'Lower leaflet 38'), ('UP39', 'Upper leaflet 39'), ('LO39', 'Lower leaflet 39'), ('UP40', 'Upper leaflet 40'), ('LO40', 'Lower leaflet 40'), ('UP41', 'Upper leaflet 41'), ('LO41', 'Lower leaflet 41'), ('UP42', 'Upper leaflet 42'), ('LO42', 'Lower leaflet 42'), ('UP43', 'Upper leaflet 43'), ('LO43', 'Lower leaflet 43'), ('UP44', 'Upper leaflet 44'), ('LO44', 'Lower leaflet 44'), ('UP45', 'Upper leaflet 45'), ('LO45', 'Lower leaflet 45'), ('UP46', 'Upper leaflet 46'), ('LO46', 'Lower leaflet 46'), ('UP47', 'Upper leaflet 47'), ('LO47', 'Lower leaflet 47'), ('UP48', 'Upper leaflet 48'), ('LO48', 'Lower leaflet 48'), ('UP49', 'Upper leaflet 49'), ('LO49', 'Lower leaflet 49'), ('UP50', 'Upper leaflet 50'), ('LO50', 'Lower leaflet 50'), ('UP51', 'Upper leaflet 51'), ('LO51', 'Lower leaflet 51'), ('UNK', 'Not in leaflet')], default='UP', max_length=4),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='prot',
            field=models.ManyToManyField(blank=True, to='membranes.MembraneProt'),
        ),
    ]
