# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import membranes.models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0035_auto_20200402_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='mem_file',
            field=models.FileField(blank=True, help_text='.pdb and .gro files are supported', null=True, upload_to=membranes.models.directory_path, validators=[membranes.models.validate_file_extension, membranes.models.validate_mem_size]),
        ),
    ]
