# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('journal', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=30, null=True)),
                ('pages', models.CharField(max_length=30, null=True)),
                ('year', models.CharField(max_length=4)),
                ('doi', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
