# Generated by Django 2.2.12 on 2020-04-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('given', models.CharField(max_length=50)),
                ('familly', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(help_text='Format: AuthorYear[Index]', max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=30, null=True)),
                ('year', models.PositiveSmallIntegerField(validators=[homepage.models.validate_year])),
                ('doi', models.CharField(max_length=100, null=True, unique=True, validators=[homepage.models.validate_doi])),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ManyToManyField(through='homepage.AuthorsList', to='homepage.Author')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='authorslist',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Reference'),
        ),
    ]
