# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='pages',
        ),
    ]
