# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 20:09
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_remove_reference_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='num',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='reference',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 12, 19, 20, 8, 44, 390516, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='refid',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
