# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models

import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171219_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[homepage.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.IntegerField(validators=[homepage.models.validate_year]),
        ),
    ]
