# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20171220_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='refid',
            field=models.CharField(help_text=b'Format: AuthorYear[Index]', max_length=200, unique=True),
        ),
    ]
