# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171220_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='authors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
