# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-02 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0010_auto_20181012_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('given', models.CharField(max_length=50)),
                ('familly', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='reference',
            name='authors',
        ),
        migrations.AddField(
            model_name='authorslist',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Reference'),
        ),
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.ManyToManyField(through='homepage.AuthorsList', to='homepage.Author'),
        ),
    ]
