# Generated by Django 2.2.13 on 2021-02-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membranes', '0002_auto_20210204_0628'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LI_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(blank=True, max_length=100)),
                ('prop', models.CharField(choices=[('APL', 'Area per lipid'), ('THK', 'Thickness'), ('ORD', 'Order parameter')], default='APL', max_length=3)),
                ('data_file', models.FileField(blank=True, help_text='Only .xvg files are supported', null=True, upload_to=properties.models.directory_path, validators=[properties.models.validate_file_extension, properties.models.validate_file_size])),
                ('index', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membranetopol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membranes.MembraneTopol')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.AnalysisSoftware')),
            ],
        ),
    ]
