# Generated by Django 2.2.12 on 2020-04-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(choices=[('AC', 'Academic'), ('CO', 'Commercial')], default='AC', max_length=2)),
                ('institution', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('miscellaneous', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
