# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='institute',
            new_name='institution',
        ),
    ]
