# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-19 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180919_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='miscellaneous',
        ),
    ]
