# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180919_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='miscellaneous',
            field=models.TextField(blank=True),
        ),
    ]
