# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180919_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='utype',
            field=models.CharField(choices=[('AC', 'Academic'), ('CO', 'Commercial')], default='AC', max_length=2),
        ),
    ]
