# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import forcefields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forcefield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('forcefield_type', models.CharField(choices=[(b'AA', b'All atom'), (b'UA', b'United atom'), (b'CG', b'Coarse grained')], default=b'AA', max_length=2)),
                ('ff_file', models.FileField(help_text=b'Use a zip file containing the forcefield directory as in <link>', upload_to=forcefields.models.ff_path)),
                ('mdp_file', models.FileField(help_text=b'Use a zip file containing the mdps for the version X of Gromacs as in <link>', upload_to=forcefields.models.mdp_path)),
                ('software', models.CharField(choices=[(b'GR', b'Gromacs')], default=b'GR', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('reference', models.ManyToManyField(to='homepage.Reference')),
            ],
        ),
    ]
