# Generated by Django 2.2.12 on 2020-04-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forcefields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Forcefield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('forcefield_type', models.CharField(choices=[('AA', 'All atom'), ('UA', 'United atom'), ('CG', 'Coarse grained')], default='AA', max_length=2)),
                ('ff_file', models.FileField(help_text='Use a zip file containing the forcefield directory', upload_to=forcefields.models.ff_path, validators=[forcefields.models.validate_file_extension, forcefields.models.validate_ff_size])),
                ('mdp_file', models.FileField(help_text='Use a zip file containing the mdps for the version X of Gromacs', null=True, upload_to=forcefields.models.mdp_path, validators=[forcefields.models.validate_file_extension, forcefields.models.validate_mdp_size])),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ManyToManyField(to='homepage.Reference')),
                ('software', models.ManyToManyField(to='forcefields.Software')),
            ],
        ),
        migrations.CreateModel(
            name='FfComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('forcefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forcefields.Forcefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
