# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forcefields', '0002_auto_20171122_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcefield',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
