# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0003_forcefield_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR', b'Gromacs'), (b'NA', b'NAMD')], default=b'GR', max_length=2),
        ),
    ]
