# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0004_auto_20180122_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR', b'Gromacs')], default=b'GR', max_length=2),
        ),
    ]
