# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import forcefields.models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0007_auto_20180607_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='ff_file',
            field=models.FileField(help_text=b'Use a zip file containing the forcefield directory', upload_to=forcefields.models.ff_path, validators=[forcefields.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='mdp_file',
            field=models.FileField(help_text=b'Use a zip file containing the mdps for the version X of Gromacs', upload_to=forcefields.models.mdp_path, validators=[forcefields.models.validate_file_extension]),
        ),
    ]
