# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0008_auto_20180914_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR45', b'Gromacs <= 4.5'), (b'GR50', b'Gromacs >= 5.0')], default=b'GR50', max_length=4),
        ),
    ]
