# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0009_auto_20181004_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='software',
            field=models.CharField(choices=[(b'AM', b'Amber'), (b'CH', b'Charmm'), (b'GR45', b'Gromacs 4.5'), (b'GR50', b'Gromacs 5.0')], default=b'GR50', max_length=4),
        ),
    ]
