# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0013_software_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='order',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
