# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import forcefields.models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0014_software_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='mdp_file',
            field=models.FileField(help_text=b'Use a zip file containing the mdps for the version X of Gromacs', null=True, upload_to=forcefields.models.mdp_path, validators=[forcefields.models.validate_file_extension]),
        ),
    ]
