# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import forcefields.models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0015_auto_20181111_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcefield',
            name='ff_file',
            field=models.FileField(help_text=b'Use a zip file containing the forcefield directory', upload_to=forcefields.models.ff_path, validators=[forcefields.models.validate_file_extension, forcefields.models.validate_ff_size]),
        ),
        migrations.AlterField(
            model_name='forcefield',
            name='mdp_file',
            field=models.FileField(help_text=b'Use a zip file containing the mdps for the version X of Gromacs', null=True, upload_to=forcefields.models.mdp_path, validators=[forcefields.models.validate_file_extension, forcefields.models.validate_mdp_size]),
        ),
    ]
